# This is a basic workflow to help you get started with Actions

name: NewMan using Trello

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'  # Specify your Node.js version here

      # Install Newman globally
      - name: Install Newman
        run: npm install -g newman

       # Install HTMLExtra globally
      - name: Install HTMLExtra
        run: npm install -g newman-reporter-htmlextra

      # Run Newman with specified global variables
      - name: Run Newman Tests
        run: |
          newman run 'Trello.postman_collection.json' \
          -r "cli,json,junit,htmlextra"
          --global-var "API_Key=${{secrets.API_KEY}}" \
          --global-var "Token=${{secrets.TOKEN}}" \
          --global-var "BaseUrl=https://api.trello.com/1/" \
          --global-var "ListID=66dc6355b603dee2d16baa57" \
          --global-var "boardID=66dc6357b9f3a6e655961daf" \
          --global-var "OrgID=5fa7a89dd5b57b18f6ce66ff"
